on: [push]
name: adsb2mqtt_build_push_image

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/adsb2mqtt:${{ github.sha }}
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/adsb2mqtt:latest
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/adsb2mqtt:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/adsb2mqtt:latest